f=open("file.txt","r")
lines=f.readlines()         # print(f.readlines())
print(lines,type(lines))                   
f.close()


# returns the lines of a file in the form of a list 


f=open("file.txt","r")
line1=f.readline()     
line2=f.readline()     
line3=f.readline()         
print(line1) 
print(line2) 
print(line3)                   
f.close()


# line=f.readline()  
# while(line!=" "):
#     print(line)
#     line=f.readline()
# f.close()

# same task can be generated by using while loop