s=set()
number_1=int(input("Enter first number: "))
s.add(number_1)
number_2=int(input("Enter second number: "))
s.add(number_2)
number_3=int(input("Enter third number: "))
s.add(number_3)
number_4=int(input("Enter fourth number: "))
s.add(number_4)
number_5=int(input("Enter fifth number: "))
s.add(number_5)
number_6=int(input("Enter sixth number: "))
s.add(number_6)
number_7=int(input("Enter seventh number: "))
s.add(number_7)
number_8=int(input("Enter eighthth number: "))
s.add(number_8)
print(s)