a='''Harry is a good boy
but not a bad boy'''
print(a)
b='''Harry is a good boy\nbut not a bad boy'''   # same output can be generated by \n and triple quotes(''' ''')
print(b)
c='''Harry is a good boy\nbut not a bad "boy"'''
print(c)
d='''Harry is a good boy\nbut not a bad \"boy\"'''  # same output can be generated by \" and double quotes in triple quotes('''"" "''')
print(d)                            